= Rapport d’avancement du groupe “x.y”
PACT groupe xy (Les plus beaux)
ifdef::env-gitlab,env-browser[:outfilesuffix: .adoc]
:doctype: book
:stem: latexmath
:source-highlighter: coderay
:toc-title: Table des matières
:toc: macro
:sectnums:
:imagesdir: images


// Partie non numérotée
:sectnums!:
== « PACT 3.5 »

=== Membres du groupe

* BECART Thierry
* BERNARD Clément
* CHENE Thomas
* FACUNDO Frank
* GRIRA Khaled
* NAIT SAAD Thiziri

=== Tuteur

* SAUVAGE Laurent

=== Encadrant génie logiciel

* MOISSINAC Jean-Claude

== Résumé du sujet choisi en français (PAN1)

*_Note: 15 lignes max_*



Notre projet vise à faire évoluer la manière dont nous appréhendons la lecture en créant de nouvelles sensations par une augmentation du nombre de sens utilisés lors de la lecture. 
Cela se manifestera sous deux formes: mobile, l’écoute d’ambiances sonores
(automatiquement ou programmées) avec des écouteurs vous encapsulera dans la lecture et une diffusion en plus d’odeurs lorsque vous êtes chez vous grâce à notre boîtier nommé Magic Box. 
Ce projet est pluridisciplinaire, en effet la conception de la Magic Box, la détermination automatique d’ambiances et de sentiments à partir d’un texte, la création de l’application mobile et l’intégration de tout cela nécessite des compétences très variées et qui correspondent aux intérêts de chacun dans le groupe.


== English Summary (PAN1)

*_Note : 15 lignes max, version anglaise du texte précédent_*


Our project aims to change how people think about reading by making it an experience that mobilizes all your senses. Two ways we will do it, one adding on the other: with headphones you’ll hear sounds that are adapted to your reading wherever you are and when you’re at home our Magic Box will also spray smells that are linked to the vibe of your reading.
 
This project is  multidisciplinary: designing the Magic Box, automatically determining the ambience of a text, crating the app and integrating everything will require various skills. Everybody in the group has something of interest to them in this project. 


*Notes concenant le rapport*

Les différentes pages du document sont rédigées en utilisant le langage
AsciiDoc. Le squelette de rapport contient des exemples avec entre autre:

* des images,
* des liens,
* des équations.

La structure du rapport (parties, sections et la relation avec les
differents fichiers) se trouve dans le fichier courant.

// en PDF on ne peut pas controler la position de la toc
// Macros non supportées
ifndef::backend-pdf[]
== Table des matières
:toc-title:
toc::[]
endif::[]

// On numérote le reste des sections
:sectnums:

== Étude d’antériorité et justification de la proposition (PAN1)

include::proposition/proposition.adoc[Description de la proposition]

include::proposition/etat-de-l-art.adoc[Description de l’état de l’art]

== Scénarios d’usage (PAN1)

include::scenario/scenario.adoc[Scénarios d’usage]

<<<

== Architecture du projet (PAN1)

include::architecture/schema.adoc[Schéma d’architecture]

include::architecture/interfaces.adoc[Description des interfaces]

include::architecture/sequence.adoc[Diagramme de séquence]

include::architecture/ihm.adoc[Interface utilisateur graphique]

include::architecture/taches.adoc[Tableau détaillé des tâches]

<<<

== Organisation du projet (PAN1)

include::organisation/planification.adoc[Diagramme de planification temporel des tâches]

include::organisation/repartition.adoc[Répartition des élèves par module]

include::organisation/plan-tests.adoc[Plans de test (PAN2+)]

include::organisation/avancement.adoc[Diagramme d’avancement des tâches (PAN2+)]

<<<

[bibliography]
== Bibliographie (PAN1+)

include::References.adoc[Bibliographie]

<<<

== Annexes

include::annexes/BasePAN1.adoc[Base de données]

include::annexes/ComclientPAN1.adoc[Communication Client Serveur]

include::annexes/modifications.adoc[Modifications (PAN2+)]

include::annexes/reunions.adoc[Comptes Rendus de réunions]

include::annexes/avancement.adoc[Avancement des modules]

include::annexes/moduleX.adoc[Avancement module X]

include::annexes/moduleY.adoc[Avancement module Y]
