=== Questionnaire publique cible

Notre projet vise à faire évoluer la manière dont nous appréhendons la lecture. Ainsi, nous voulons
créer de nouvelles sensations par une augmentation du nombre de sens utilisés lors de notre lecture. Cela
pourra se déployer sous deux formes : une forme mobile avec la mise en place d’ambiances sonores (au-
tomatique ou programmée) avec des écouteurs ou bien une diffusion odeurs/sons lorsque vous êtes chez
vous. Nous devons alors avoir l’avis de notre cible, qui serait à la fois une population dont la lecture est
une habitude, pour vous faire découvrir une nouvelle dimension à celle-ci, et à la fois un jeune public qui
n’a pas forcément une grande attirance envers la lecture classique.

=== Questions

1. Aimez-vous lire ou aimeriez-vous lire plus ?
2. A quelle fréquence lisez-vous ?
3. Quelle est la durée de lecture que vous avez à chaque fois que vous lisez ?
4. Quel genre de lecture préférez-vous ?
5. Quel est la taille moyenne de votre lecture (comme par exemple des lectures sur in-
ternet)
6. Que faites vous lorsque vous lisez ? (exemple : écouter de la musique)
7. Avez vous des problèmes d’inattention lors de votre lecture ? Pourquoi ?
8. Etes vous capable de lire dans des lieux publics sans musique ?
9. Comment vivez-vous la lecture ? Vous sentez-vous comme dans une ”bulle” ?
10. Aimeriez-vous être comme dans une bulle lorsque vous ”lisez” ?
11. Que pensez-vous d’une ambiance sonore jouée en même temps que votre lecture,
adaptée au thème de la page lue ?
12. Même question pour des odeurs.
113. Vous ennuyez-vous après un certain temps de lecture ?
14. Où lisez vous le plus souvent ? (dans quelle position)
15. Comment aviez vous vécu la transition entre les ”Tom tom et Nana” aux romans/nouvelles
de Victor Hugo par exemple ? Etes vous passez par des nouvelles, ou des romans ?
16. Comment pensez vous pouvoir faciliter cette transition ?
17. Comment achetez-vous vos livres ? Internet, magasins ?
18. Sur quel support lisez-vous ?
19. Jusqu’à combien êtes-vous prêt à investir pour la lecture ?
